#!/usr/bin/env bash
# weekly-check.sh — Sunday-morning hygiene check for oregon-trail.
#
# Two habits Ryan flagged after 2026-04-21 retro:
#   - Pre-merge kaplay-rebuild → master weekly, keep divergence < 10 commits
#   - Archive stale *_PLAN.md files at repo root after feature ships
#
# This script:
#   1. fetches origin
#   2. counts commits between origin/master and origin/kaplay-rebuild
#   3. flags if divergence > 10
#   4. lists *_PLAN.md files at repo root untouched for > 3 days
#      (candidates to archive via scripts/archive-plan.sh)
#   5. logs findings to ~/.gstack/projects/oregon-trail/HEALTH.md
#
# Exits 0 if healthy, 1 if action needed. Cron surfaces any stderr
# output via local MAILTO or the tail of HEALTH.md.
#
# Cron line (Sunday 08:00 local):
#   0 8 * * 0 cd /home/ryan/code/oregon-trail && scripts/weekly-check.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

HEALTH_DIR="$HOME/.gstack/projects/oregon-trail"
HEALTH_FILE="$HEALTH_DIR/HEALTH.md"
DIVERGENCE_THRESHOLD=10
STALE_DAYS=3

mkdir -p "$HEALTH_DIR"

TS=$(date +"%Y-%m-%d %H:%M")
STATUS_BLOCK=""
EXIT_CODE=0

# ── 1. Branch divergence ────────────────────────────────
git fetch origin master kaplay-rebuild --quiet 2>&1 || true

# Commits on kaplay-rebuild not yet on master.
AHEAD=$(git rev-list --count origin/master..origin/kaplay-rebuild 2>/dev/null || echo 0)
# Commits on master not yet on kaplay-rebuild (unusual — may mean hotfix
# landed on master without merging back).
BEHIND=$(git rev-list --count origin/kaplay-rebuild..origin/master 2>/dev/null || echo 0)

if [ "$AHEAD" -gt "$DIVERGENCE_THRESHOLD" ]; then
  STATUS_BLOCK="${STATUS_BLOCK}
- ⚠ kaplay-rebuild is ${AHEAD} commits ahead of master (threshold: ${DIVERGENCE_THRESHOLD}).
  Merge soon so deploys stay obvious:
    git checkout master && git merge kaplay-rebuild && git push origin master
"
  EXIT_CODE=1
fi

if [ "$BEHIND" -gt 0 ]; then
  STATUS_BLOCK="${STATUS_BLOCK}
- ⚠ master is ${BEHIND} commits ahead of kaplay-rebuild (hotfix not merged back?).
  Review: git log origin/kaplay-rebuild..origin/master --oneline
"
  EXIT_CODE=1
fi

if [ "$AHEAD" -le "$DIVERGENCE_THRESHOLD" ] && [ "$BEHIND" -eq 0 ]; then
  STATUS_BLOCK="${STATUS_BLOCK}
- ✓ Branch divergence: ${AHEAD} ahead, ${BEHIND} behind. Healthy.
"
fi

# ── 2. Stale plan files ─────────────────────────────────
# *_PLAN.md or *_STATUS.md at repo root not touched in N days.
STALE_FILES=""
while IFS= read -r f; do
  [ -n "$f" ] && STALE_FILES="${STALE_FILES}  - ${f}"$'\n'
done < <(find . -maxdepth 1 -type f \( -name "*_PLAN.md" -o -name "*_STATUS.md" \) -mtime +${STALE_DAYS} 2>/dev/null | sed 's|^\./||')

if [ -n "$STALE_FILES" ]; then
  STATUS_BLOCK="${STATUS_BLOCK}
- Stale plan files (untouched > ${STALE_DAYS} days) — consider archiving:
${STALE_FILES}
  Archive one: scripts/archive-plan.sh <file>
"
fi

# ── 3. Write health log ─────────────────────────────────
# Prepend the new entry so the latest run is at the top.
NEW_ENTRY="## ${TS}${STATUS_BLOCK}
"

if [ -f "$HEALTH_FILE" ]; then
  TMP=$(mktemp)
  { printf "%s" "$NEW_ENTRY"; cat "$HEALTH_FILE"; } > "$TMP"
  mv "$TMP" "$HEALTH_FILE"
else
  {
    echo "# Oregon Trail — Weekly Health Log"
    echo ""
    echo "Generated by \`scripts/weekly-check.sh\`. Latest run first."
    echo ""
    printf "%s" "$NEW_ENTRY"
  } > "$HEALTH_FILE"
fi

# ── 4. Output ───────────────────────────────────────────
# Send to stderr so cron captures and mails it if MAILTO is set.
if [ "$EXIT_CODE" -ne 0 ]; then
  echo "[weekly-check] ACTION NEEDED — ${TS}" >&2
  printf "%s" "$STATUS_BLOCK" >&2
  echo "" >&2
  echo "Full log: $HEALTH_FILE" >&2
else
  echo "[weekly-check] all healthy — ${TS}"
  printf "%s" "$STATUS_BLOCK"
fi

exit "$EXIT_CODE"
